version: '3.9'

services:
  productpage-43:
    build: 
      context: .
      dockerfile: ProductPage/Dockerfile
    ports: 
      - "9080:9080"
  details-43:
     build: 
      context: .
      dockerfile: Details/Dockerfile
     environment:
      - SERVICE_VERSION=v1
      - ENABLE_EXTERNAL_BOOK_SERVICE=true
  
  ratings-43:
     build: 
      context: .
      dockerfile: Ratings/Dockerfile
     environment:
      - SERVICE_VERSION=v1
      - ENABLE_RATINGS=true
  reviews-43:
     image: "g43/ratings:latest"
    

