version: '3'

services:
  productpage:
    build:
      context: .
      dockerfile: ProductPage/Dockerfile
    environment:
      GROUP_NUM: g43
    ports:
      - "9080:9080"
    container_name: "product-page-g43"
    image: "product-page/g43"
  
  details:
    build:
      context: .
      dockerfile: Details/Dockerfile
    environment:
      SERVICE_VERSION: v1
      ENABLE_EXTERNAL_BOOK_SERVICE: "true"
    container_name: "details-g43"
    image: "details/g43"
  
  ratings:
    build:
      context: .
      dockerfile: Ratings/Dockerfile
    environment:
      SERVICE_VERSION: v1
    container_name: "ratings-g43"
    image: "ratings/g43"

  
 
