version: '3.9'

services:
  productpage-g43:
    build: 
      context: .
      dockerfile: ProductPage/Dockerfile
    container_name: productpage-g43
    image: 
      productpage/g43
    ports: 
      - "9080:9080"
  details-g43:
     build: 
      context: .
      dockerfile: Details/Dockerfile
     container_name: details-g43
     image: 
      details/g43
     environment:
      - SERVICE_VERSION=v1
      - ENABLE_EXTERNAL_BOOK_SERVICE=true
  
  ratings-g43:
     build: 
      context: .
      dockerfile: Ratings/Dockerfile
     container_name: ratings-g43
     image: 
      ratings/g43
     environment:
      - SERVICE_VERSION=v1
      - ENABLE_RATINGS=true
  reviews-g43:
     container_name: reviews-g43
     image: reviews/g43
     environment:
      - SERVICE_VERSION=v1
      - ENABLE_RATINGS=true
      - STAR_COLOR=black  
    

