apiVersion: apps/v1
kind: Deployment
metadata:
  name: details
spec:
  replicas: 3
  selector:
    matchLabels:
      app: details
  template:
    metadata:
      labels:
        app: details
    spec:
      containers:
      - name: details
        image: Zohard02/details
        ports:
        - containerPort: 9080
        env:
        - name: SERVICE_VERSION
          value: "v1"
        - name: ENABLE_EXTERNAL_BOOK_SERVICE
          value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: details
spec:
  selector:
    app: details
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9080
  type: ClusterIP