apiVersion: apps/v1
kind: Deployment
metadata:
  name: ratings
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ratings
  template:
    metadata:
      labels:
        app: ratings
    spec:
      containers:
      - name: ratings-g43
        image: victornp/ratings
        ports:
        - containerPort: 9080
        env:
        - name: SERVICE_VERSION
          value: "v1"
---
apiVersion: v1
kind: Service
metadata:
  name: ratings
spec:
  selector:
    app: ratings
  ports:
    - protocol: TCP
      port: 9080
      targetPort: 9080
  type: ClusterIP