apiVersion: apps/v3
kind: Deployment
metadata:
  name: reviews-v3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reviews
      version: v3
  template:
    metadata:
      labels:
        app: reviews
        version: v3
    spec:
      containers:
      - name: reviews-g43
        image: victornp/reviews-v3
        ports:
        - containerPort: 9080
        env:
        - name: SERVICE_VERSION
          value: "v3"
        - name: ENABLE_RATING
          value: "false"
        - name: STAR_COLOR
          value: "red"

apiVersion: v1
kind: Service
metadata:
  name: reviews
spec:
  selector:
    app: reviews
  ports:
    - protocol: TCP
      port: 9080
      targetPort: 9080
  type: ClusterIP