apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviews-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reviews
      version: v2
  template:
    metadata:
      labels:
        app: reviews
        version: v2
    spec:
      containers:
      - name: reviews-g43
        image: victornp/reviews-v2
        ports:
        - containerPort: 9080
        env:
        - name: SERVICE_VERSION
          value: "v2"
        - name: ENABLE_RATINGS
          value: "true"
        - name: STAR_COLOR
          value: "black"
---
apiVersion: v1
kind: Service
metadata:
  name: reviews
spec:
  selector:
    app: reviews
  ports:
    - protocol: TCP
      port: 9080
      targetPort: 9080
  type: ClusterIP