apiVersion: apps/v1
kind: Deployment
metadata:
  name: productpage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productpage
  template:
    metadata:
      labels:
        app: productpage
    spec:
      containers:
      - name: productpage
        image: productpage/g43
        ports:
        - containerPort: 9080
        env:
        - name: GROUP_NUM
          value: "1"