apiVersion: apps/v1
kind: Deployment
metadata:
  name: ratings
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ratings
  template:
    metadata:
      labels:
        app: ratings
    spec:
      containers:
      - name: ratings
        image: ratings/g43
        ports:
        - containerPort: 9080
        env:
        - name: SERVICE_VERSION
          value: "v1"