apiVersion: apps/v3
kind: Deployment
metadata:
  name: reviews-v3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reviews
      version: v3
  template:
    metadata:
      labels:
        app: reviews
        version: v3
    spec:
      containers:
      - name: reviews
        image: reviews/g43
        ports:
        - containerPort: 9080
        env:
        - name: SERVICE_VERSION
          value: "v3"
